spring.datasource.url=jdbc:postgresql://ep-shy-bonus-azd5ml30-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_XyAFR7p9VeDx
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true